# Generated by Django 2.0.6 on 2018-10-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('llave', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', '-id'],
                'verbose_name_plural': 'llaves de tiendas',
                'abstract': False,
                'verbose_name': 'llave de tienda',
                'db_table': 'tienda_token',
            },
        ),
    ]
