# Generated by Django 2.0.6 on 2019-02-15 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_auto_20181201_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricacion',
            options={'ordering': ['-fecha_ultima_modificacion', '-id'], 'permissions': (('view_fabricacion', 'Can see fabricacion'),), 'verbose_name': 'fabricación'},
        ),
        migrations.AlterField(
            model_name='fabricacion',
            name='unidad_inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricacion', to='almacenes.UnidadInventario'),
        ),
    ]
