# Generated by Django 2.0.6 on 2019-02-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_auto_20190215_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costocompra',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
