# Generated by Django 2.0.6 on 2019-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_auto_20190219_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En proceso'), (2, 'Finalizada'), (3, 'Pausada'), (4, 'Cancelada')]),
        ),
    ]
