# Generated by Django 2.0.6 on 2018-10-17 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', '-id'],
                'db_table': 'atributo_categoria',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtributoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('valor', models.CharField(max_length=255)),
                ('atributo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.AtributoCategoria')),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', '-id'],
                'db_table': 'atributo_producto',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('ultimo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_productos_categoriaproducto', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por')),
            ],
            options={
                'ordering': ('nombre',),
                'permissions': (('view_categoriaproducto', 'Can see categorias productos'),),
                'verbose_name_plural': 'categorías',
                'verbose_name': 'categoría',
                'abstract': False,
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='ComponenteProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('cantidad_componente', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', '-id'],
                'db_table': 'componente_producto',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('codigo_venta', models.CharField(max_length=45, verbose_name='código de venta')),
                ('descripcion', models.CharField(max_length=45, verbose_name='descripción')),
                ('balanza', models.BooleanField(default=False)),
                ('producto_pre_fabricado', models.BooleanField(default=False, verbose_name='producto pre-fabricado')),
                ('limite_venta_persona', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='límite de venta por persona')),
                ('periodo_venta_producto', models.SmallIntegerField(blank=True, choices=[(1, 'Diario'), (2, 'Semanal')], null=True, verbose_name='periodo del límite de venta')),
                ('seguimiento', models.SmallIntegerField(blank=True, choices=[(1, 'Lote'), (2, 'Número de serie')], null=True, verbose_name='tipo de seguimiento')),
                ('slug', models.SlugField(unique=True)),
                ('atributos_categoria', models.ManyToManyField(through='productos.AtributoProducto', to='productos.AtributoCategoria')),
                ('componentes', models.ManyToManyField(through='productos.ComponenteProducto', to='productos.Producto')),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', '-id'],
                'permissions': (('view_producto', 'Can see productos'),),
                'db_table': 'producto',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_producto', to='productos.Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_proveedor', to='personas.Persona')),
                ('ultimo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_productos_proveedorproducto', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por')),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', '-id'],
                'db_table': 'proveedor_producto',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('ultimo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_productos_unidad', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por')),
            ],
            options={
                'ordering': ('nombre',),
                'permissions': (('view_unidad', 'Can see unidades'),),
                'verbose_name_plural': 'unidades',
                'abstract': False,
                'db_table': 'unidad',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(through='productos.ProveedorProducto', to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultimo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_productos_producto', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.Unidad'),
        ),
        migrations.AddField(
            model_name='componenteproducto',
            name='producto_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_producto', to='productos.Producto'),
        ),
        migrations.AddField(
            model_name='componenteproducto',
            name='producto_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compuestos', to='productos.Producto'),
        ),
        migrations.AddField(
            model_name='componenteproducto',
            name='ultimo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_productos_componenteproducto', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por'),
        ),
        migrations.AddField(
            model_name='atributoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='productos.Producto'),
        ),
        migrations.AddField(
            model_name='atributoproducto',
            name='ultimo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_productos_atributoproducto', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por'),
        ),
        migrations.AddField(
            model_name='atributocategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='productos.CategoriaProducto'),
        ),
        migrations.AddField(
            model_name='atributocategoria',
            name='ultimo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_productos_atributocategoria', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por'),
        ),
    ]
