# Generated by Django 2.0.6 on 2019-02-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'ordering': ('nombre',), 'permissions': (('view_categoriaproducto', 'Can see categorías productos'),), 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
    ]
