# Generated by Django 2.0.6 on 2018-10-17 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('ultimo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_tiendas_tienda', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por')),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', '-id'],
                'db_table': 'tienda',
                'abstract': False,
            },
        ),
    ]
