# Generated by Django 2.0.6 on 2019-02-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tienda',
            options={'ordering': ['-fecha_ultima_modificacion', '-id'], 'permissions': (('view_tienda', 'Can see tiendas'),)},
        ),
    ]
