# Generated by Django 2.0.6 on 2018-10-17 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_inventario', to='productos.Producto'),
        ),
        migrations.AddField(
            model_name='unidadinventario',
            name='ultimo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_almacenes_unidadinventario', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por'),
        ),
        migrations.AddField(
            model_name='preciounidadinventario',
            name='ultimo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_almacenes_preciounidadinventario', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por'),
        ),
        migrations.AddField(
            model_name='preciounidadinventario',
            name='unidad_inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='almacenes.UnidadInventario'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_produccion', to='productos.Producto'),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='ultimo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_almacenes_loteproduccion', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='tiendas.Tienda'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='ultimo_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_almacenes_almacen', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por'),
        ),
    ]
