# Generated by Django 2.0.6 on 2018-12-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0005_auto_20181201_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlstock',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='stock máximo'),
        ),
    ]
