# Generated by Django 2.0.6 on 2018-12-01 07:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacenes', '0006_auto_20181201_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariofisico',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_fisicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidadinventariofisico',
            name='cantidad_producto',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Cantidad de producto'),
        ),
    ]
