# Generated by Django 2.0.6 on 2018-12-18 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0007_auto_20181201_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlstock',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='almacenes.Almacen', verbose_name='almacén'),
        ),
        migrations.AlterField(
            model_name='controlstock',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='stock máximo'),
        ),
        migrations.AlterField(
            model_name='inventariofisico',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_fisicos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de creación'),
        ),
    ]
