# Generated by Django 2.0.6 on 2019-02-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0008_auto_20181217_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciounidadinventario',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
