# Generated by Django 2.0.6 on 2018-10-17 03:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última modificación')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.CharField(max_length=1, verbose_name='tipo de identificación')),
                ('numero_identificacion', models.CharField(max_length=45, verbose_name='número de identificación')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=45, null=True, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='dirección de correo electrónico')),
                ('twitter', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', "Solo se permiten caracteres alfanuméricos y '_'.")])),
                ('instagram', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\.]*$', "Solo se permiten caracteres alfanuméricos, '.' y '_'.")])),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^[0-9a-zA-Z\\.]*$', "Solo se permiten caracteres alfanuméricos y '.'.")])),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.Persona')),
                ('ultimo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_personas_persona', to=settings.AUTH_USER_MODEL, verbose_name='modificado la última vez por')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ultima_modificacion', '-id'],
                'permissions': (('view_persona', 'Can see personas'),),
                'db_table': 'persona',
                'abstract': False,
            },
        ),
    ]
